### ISSUE TITLE
'The MaxMind DB file's search tree is corrupt' message when opening GeoLite2 database

### ISSUE THREAD

**Issue by yhirose** [maxmind/MaxMind-DB-Reader-ruby#32]
Since the download policy has been changed recently for GeoLite2 database, I downloaded it (GeoLite2-Country_20200107.mmdb) based on the following information:
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

Then I tried to run the sample code on README with the downloaded database. But I got '**The MaxMind DB file's search tree is corrupt**' error message.

```ruby
require 'maxmind/db'

# reader = MaxMind::DB.new('GeoIP2-City.mmdb', mode: MaxMind::DB::MODE_MEMORY)
reader = MaxMind::DB.new('GeoLite2-Country_20200107.mmdb', mode: MaxMind::DB::MODE_MEMORY)

record = reader.get('1.1.1.1')
if record.nil?
  puts '1.1.1.1 was not found in the database'
else
  puts record['country']['iso_code']
  puts record['country']['names']['en']
end

reader.close
```

```bash
[master] ~/Projects/MaxMind-DB-Reader-ruby$ ruby a.rb
Traceback (most recent call last):
	3: from a.rb:6:in `<main>'
	2: from /Library/Ruby/Gems/2.6.0/gems/maxmind-db-1.1.0/lib/maxmind/db.rb:139:in `get'
	1: from /Library/Ruby/Gems/2.6.0/gems/maxmind-db-1.1.0/lib/maxmind/db.rb:171:in `get_with_prefix_length'
/Library/Ruby/Gems/2.6.0/gems/maxmind-db-1.1.0/lib/maxmind/db.rb:262:in `resolve_data_pointer': The MaxMind DB file's search tree is corrupt (MaxMind::DB::InvalidDatabaseError)
```

I wondered whether the downloaded data was corrupted, or this gem had a problem. But I tested the same database with my gem (https://github.com/yhirose/maxminddb) and got exactly the save error. So I believe it's a data issue.

Please let me know if there is a better place where I can report this issue.
Thanks!

**Comment by oschwald** [comment]
I tested the above code with the 2020-01-06 GeoLite2 Country database and it worked for me. Are you sure you are untarring the file? Previously the file was distributed both as a `gz` file (without tar) and a `tar.gz` file. The download provided in our account portal is a `tar.gz` file.

**Comment by yhirose** [comment]
@oschwald, y the file as `gz`... The sample now worked fine and returns `AU Australia` as expected.
Thanks for your help!
