### ISSUE TITLE
Messy `inspect` output when using MODE_MEMORY

### ISSUE THREAD

**Issue by morgoth** [maxmind/MaxMind-DB-Reader-ruby#6]
When running in console / irb code `MaxMind::DB.new("tmp/GeoLite2-City.mmdb", mode: MaxMind::DB::MODE_MEMORY)` output contains binary data like: "\\x00\\x03\\x06\\xFF\\x03\\x05\\xE1\\x00\\x03\\x06\\x9B\\x03\\x05\\xE2\\x00\\x03\\x06)\\x03\\x05\\xE3\\x00\\x03\\x06\\x05\\x03\\x05\\xE4\\x00\\x03\\x05\\xF4\\x03\\x05\\xE5\\x00\\x03\\x05\\xEB\\x8AE" which is huge and it makes irb session almost unresponsive.

I guess it's because `inspect` (which is implicitly called in such situation) tries to display all instance variables by default.

**Comment by horgh** [comment]
Thanks for mentioning this! Yeah, that is not ideal. I've made a change in #7 that should avoid this.

**Comment by morgoth** [comment]
Thank you. Now it works fine.
